// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_wicOos-yjnoAOqnttLwNUI4CtV5sJ8',
    appId: '1:159428964016:web:5f7ba46e7e7dd0822d5575',
    messagingSenderId: '159428964016',
    projectId: 'message-board-app-55e8b',
    authDomain: 'message-board-app-55e8b.firebaseapp.com',
    storageBucket: 'message-board-app-55e8b.firebasestorage.app',
    measurementId: 'G-TGSR1TT9J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6d8I7NzeZUkcXeF9wkn9zdhyrvjTKQIc',
    appId: '1:159428964016:android:b55aff944b9816c12d5575',
    messagingSenderId: '159428964016',
    projectId: 'message-board-app-55e8b',
    storageBucket: 'message-board-app-55e8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9KeDZr7EIDKy0QE2WC98Y0_JZP1ngfo',
    appId: '1:159428964016:ios:e2815d0c0e9a49632d5575',
    messagingSenderId: '159428964016',
    projectId: 'message-board-app-55e8b',
    storageBucket: 'message-board-app-55e8b.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9KeDZr7EIDKy0QE2WC98Y0_JZP1ngfo',
    appId: '1:159428964016:ios:e2815d0c0e9a49632d5575',
    messagingSenderId: '159428964016',
    projectId: 'message-board-app-55e8b',
    storageBucket: 'message-board-app-55e8b.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD_wicOos-yjnoAOqnttLwNUI4CtV5sJ8',
    appId: '1:159428964016:web:d17785d29755d96e2d5575',
    messagingSenderId: '159428964016',
    projectId: 'message-board-app-55e8b',
    authDomain: 'message-board-app-55e8b.firebaseapp.com',
    storageBucket: 'message-board-app-55e8b.firebasestorage.app',
    measurementId: 'G-PSLDZNN2P7',
  );
}
